### ISSUE TITLE
Dependency issue on lighthouse-batch

### ISSUE THREAD

**Issue by SelfishLucho** [femtopixel/docker-google-lighthouse-puppeteer#4]
**Description**
I keep hitting this:

> rm: could not remove directory (code EBUSY): /home/chrome/reports
TypeError: Cannot read property 'reduce' of undefined

Briefly describe the problem you are having in a few paragraphs.

when running:

> docker run --rm --name perf -it -v /path/to/your/report/folder:/home/chrome/reports -v /path/to/your/testcases/folder:/home/chrome/testcases --security-opt seccomp=$HOME/chrome.json femtopixel/google-lighthouse-puppeteer <name_of_the_test>

and it might be due to this [issue](https://github.com/mikestead/lighthouse-batch/issues/4)?

**Command line I used to start the container**

docker run --rm --name perf -it -v /path/to/your/report/folder:/home/chrome/reports -v /path/to/your/testcases/folder:/home/chrome/testcases --security-opt seccomp=$HOME/chrome.json femtopixel/google-lighthouse-puppeteer <name_of_the_test>

**Describe the results you received:**

rm: could not remove directory (code EBUSY): /home/chrome/reports
TypeError: Cannot read property 'reduce' of undefined

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs perf`)**

<details>
<pre>
no generated logs
</pre>
</details>

**Output of `docker inspect perf --format='{{index .Config.Labels.version}}'`:**

```
v1.11.0
```

**Comment by jaymoulin** [comment]
That version number is disturbing me... I think I messed up with one of my minion robot :/

**Comment by jaymoulin** [comment]
This was a bit tough but it should work with the `v4.0.0-alpha.2-3.2.1-v1.11.0-0.4.1` version

**Comment by SelfishLucho** [comment]
working from my side 👍

**Comment by jaymoulin** [comment]
Feel free to donate to help me continue making great products ;)
